### ISSUE TITLE
All Components - Do backups work?

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#27]
Can I recover Hyrax from the backups created by these roles?

**Comment by cudevmaxwell** [comment]
#28 should also be checked. Does recovery mean the NOID minter state is preserved?

**Comment by orangewolf** [comment]
Minter is recovered because it is in the database properly. Backup can be restored successfully, which is good.

One question I had about the current backup setup - they sit on the server. What happens if (like an AWS instance) it goes away? I think the answer is that you backup the EBS volumes from the AWS side and it is out of scope for this lib, but I wanted to check.

**Comment by cudevmaxwell** [comment]
> Backup can be restored successfully, which is good.

Glad to have that confirmed. 🕺 

In the README, we say:

> For large deployments, this amount of backups might overwhelm local storage. It is recommended that the backup schedule and retention periods be tailored for your deployment.
> 
> It is up to local system administrators to copy backup data to a NAS or SAN, tape, or to cloud storage like Amazon Glacier or OLRC.

So for 'old-school' on-prem deployments or cloud deploys, the onus is on the system admin to move the backups somewhere more permanent.

**Comment by cudevmaxwell** [comment]
Closing, thanks for the work @orangewolf
