### ISSUE TITLE
Ansible - Update to handle Postgres 10 & 11

### ISSUE THREAD

**Issue by dewey4iv** [cu-library/hyrax-ansible#44]
Attempting to spin up a most recent version of Ubuntu 18.04 fails. This is due to Postgres no longer accepting an un-encrypted password to be set.

**Comment by cudevmaxwell** [comment]
On it.

**Comment by cudevmaxwell** [comment]
Possibly fixed in 2ec61a1. Testing using https://github.com/cu-library/hyrax-ansible-testvagrants now.

**Comment by cudevmaxwell** [comment]
I think I know what's happening: 18.04 installs Ansible 2.5.1 from the default package repos: https://packages.ubuntu.com/bionic/admin/ansible

The fix for this issue (a better default for the `encrypted` param in postgresql_user) https://docs.ansible.com/ansible/latest/modules/postgresql_user_module.html is only part of Ansible versions >= 2.6. 

The Vagrant env I set up for testing does this:

```
apt-get update && apt-get upgrade -y
apt-get install -y software-properties-common git curl
apt-add-repository -y ppa:ansible/ansible
apt-get update
apt-get install -y ansible
```
so this wasn't a problem I saw, since I always installed a newer Ansible from the ppa repo. 

2ec61a1 doesn't rely on the default, it sets the `encrypted` param explicitly.

**Comment by dewey4iv** [comment]
I actually already have a fix. I'll have a PR shortly.

**Comment by dewey4iv** [comment]
Actually @cudevmaxwell -- https://github.com/cu-library/hyrax-ansible/commit/2ec61a161d3f3b953034dfcf3796d642c7357baa is exactly what I had working.

**Comment by cudevmaxwell** [comment]
Perfect. @dewey4iv ok if I close this issue?
