### ISSUE TITLE
Java - JAVA_OPTS Does Java GC option matter?

### ISSUE THREAD

**Issue by cudevmaxwell** [cu-library/hyrax-ansible#5]
Commit ba5cd0bf4b8c3ad1356cea002e2ad2099e0eb747 removed the Java GC option. This was done because it conflicts with an existing GC option read in to configuration before setenv.sh is on Ubuntu and Debian. Does it matter?

**Comment by orangewolf** [comment]
Not really, no.  G1GC vs ConcMark is kind of a toss up for this application. ConcMark is more stable and a little slower, but G1GC tends to run more often. They are both better than the default, so that's almost certainly good enough for all but the most aggressive usecase, which would need to be tuned to one or the other based on CPU vs Memory bound tradeoffs.
